CREATE DATABASE DEPARTMENT;
USE DEPARTMENT;
CREATE TABLE DEP
(
DEP_ID INT PRIMARY KEY,
DEP_NAME VARCHAR(250) 
);
CREATE TABLE EMPLOY
(
EMP_ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(250),
PH_NO INT UNIQUE,
SALARY INT CHECK(SALARY >= 1000),
DEP_ID INT,
FOREIGN KEY (DEP_ID) REFERENCES DEP(DEP_ID)
);
DESCRIBE EMPLOY; 
