CREATE DATABASE DB;
SHOW DATABASES;
USE DB;
CREATE TABLE STUDENTS
(
ID INT,
NAME VARCHAR(50),
COURSEID INT); 
SHOW TABLES;
DESCRIBE STUDENTS;
ALTER TABLE STUDENTS ADD COLUMN COURSE_NAME VARCHAR(50);
DESCRIBE STUDENTS;
ALTER TABLE STUDENTS MODIFY COLUMN NAME CHAR(10);
ALTER TABLE STUDENTS RENAME COLUMN NAME TO STUDENT_NAME;
ALTER TABLE STUDENTS DROP COLUMN COURSE_NAME;
RENAME TABLE STUDENTS TO STUDENT_DETAIL;
DROP TABLE STUDENT_DETAIL;
DROP DATABASE DB;
SHOW DATABASES;
