CREATE DATABASE STUDENT;
USE STUDENT;
CREATE TABLE STUDENTS
(
ID INT,
NAME VARCHAR(50),
DEPARTMENT VARCHAR(50));
ALTER TABLE STUDENTS MODIFY COLUMN DEPARTMENT INT;
SHOW TABLES;
SELECT * FROM STUDENTS;
INSERT INTO STUDENTS (ID,NAME,DEPARTMENT) VALUES
(1,"ANAND",101),(2,"BABU",102),(3,"CHARU",103);
SELECT * FROM STUDENTS;
UPDATE  STUDENTS SET DEPARTMENT=103 WHERE ID=1;
SET SQL_SAFE_UPDATES=1;
DELETE FROM STUDENTS WHERE ID = 1;
SELECT * FROM STUDENTS;