USE HR;
/* SELECT - PRINT ALL THE ROLE FROM EMPLOYESS */
SELECT * FROM EMPLOYEES;
SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES;
SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID=50;
SELECT EMPLOYEE_ID , FIRST_NAME , SALARY FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 10000;
SELECT EMPLOYEE_ID , FIRST_NAME , SALARY FROM EMPLOYEES WHERE FIRST_NAME="STEVEN";
SELECT EMPLOYEE_ID , FIRST_NAME ,DEPARTMENT_ID, SALARY FROM EMPLOYEES WHERE SALARY>5000 OR DEPARTMENT_ID=50;
SELECT EMPLOYEE_ID , FIRST_NAME, DEPARTMENT_ID,SALARY,COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;
SELECT EMPLOYEE_ID , FIRST_NAME, DEPARTMENT_ID,SALARY,COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT IS  NULL;
/* like */
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%J';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%AV%';
SELECT COUNT(EMPLOYEE_ID), DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
SELECT COUNT(EMPLOYEE_ID) AS EMPLOYEE_ID,DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING EMPLOYEE_ID > 4;
SELECT COUNT(EMPLOYEE_ID) AS EMPLOYEE_ID,DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING EMPLOYEE_ID > 4 ORDER BY EMPLOYEE_ID;
SELECT COUNT(EMPLOYEE_ID) AS EMPLOYEE_ID,DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING EMPLOYEE_ID > 4 ORDER BY EMPLOYEE_ID LIMIT 2 OFFSET 2;  


