-- COMMON TECHNIQUES TO OPTIMIZE QUERY PERFORMANCE
-- 1.USE INDEXES
-- EXAMPLE:
USE HR;
CREATE INDEX IDX_SALARY ON EMPLOYEES(SALARY);
 
-- 2. DONT USE SALARY *

SELECT * FROM EMPLOYEES; -- AVOID USING *
SELECT EMPLOYEE_ID FROM EMPLOYEES;
-- USE SPECIFIC COL
-- 3. USE WHERE CLAUSE AND LIMIT:(CONDITION) 