SELECT E.EMPLOYEE_ID,E.FIRST_NAME,D.DEPARTMENT_ID FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
USE HR;
SELECT D.DEPARTMENT_ID,L.LOCATION_ID,L.CITY FROM DEPARTMENTS D INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;
SELECT D.DEPARTMENT_ID,L.LOCATION_ID,L.CITY FROM DEPARTMENTS D INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID WHERE L.CITY="TOKYO";
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,D.DEPARTMENT_NAME FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
SELECT D.DEPARTMENT_ID,L.LOCATION_ID,L.CITY FROM DEPARTMENTS D RIGHT JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;
SELECT D.DEPARTMENT_ID,L.LOCATION_ID,L.CITY FROM DEPARTMENTS D LEFT JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
UNION SELECT D.DEPARTMENT_ID,L.LOCATION_ID,L.CITY FROM DEPARTMENTS D RIGHT JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;
/* SELF JOIN */
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,M.FIRST_NAME AS MANAGER FROM EMPLOYEES E LEFT JOIN EMPLOYEES M ON E.MANAGER_ID=M.EMPLOYEE_ID;

SELECT E.EMPLOYEE_ID,E.FIRST_NAME,D.DEPARTMENT_ID,L.CITY FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
INNER JOIN LOCATIONS L ON L.LOCATION_ID=D.LOCATION_ID;
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,D.DEPARTMENT_ID,L.CITY,L.LOCATION_ID FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
INNER JOIN LOCATIONS L ON L.LOCATION_ID=D.LOCATION_ID WHERE L.CITY="LONDON";
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 1;

/* SUB QUERY - SINGLE ROW EX WHO IS TAKE HIGH SALARY IN SAME TABLE HOW MANY MEMBERS *,WE CAN ONLY USE OPERATORS*/
SELECT * FROM EMPLOYEES WHERE SALARY=(SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=50);
SELECT * FROM EMPLOYEES WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES);
SELECT * FROM EMPLOYEES WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=50);
SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=50;

/* MULTI ROWS (IN,ANY-ATLEAST,ALL-HIGH) */
SELECT * FROM EMPLOYEES WHERE SALARY IN (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID=50);
SELECT * FROM EMPLOYEES WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID=50);
SELECT * FROM EMPLOYEES WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID=50);