show databases;
use hr;
SELECT * FROM EMPLOYEES;
/*1. ROW NUMBER  RANKING FUNCTION*/

SELECT EMPLOYEE_ID , FIRST_NAME,SALARY , ROW_NUMBER() OVER (ORDER BY SALARY DESC) FROM EMPLOYEES;
SELECT EMPLOYEE_ID , FIRST_NAME,SALARY , DEPARTMENT_ID, ROW_NUMBER() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL;

/*2. RANK FUNCTION */

SELECT EMPLOYEE_ID , FIRST_NAME,SALARY , DEPARTMENT_ID, RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL;

/* DENSE RANK */

SELECT EMPLOYEE_ID , FIRST_NAME,SALARY , DEPARTMENT_ID, DENSE_RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) RANK1 FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL;

/* AGGREGATE FUNCTION */

SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID,HIRE_DATE,SALARY,SUM(SALARY) OVER (ORDER BY HIRE_DATE) AS RUNNING_TOTAL FROM EMPLOYEES;
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID,HIRE_DATE,SALARY,SUM(SALARY) OVER (ORDER BY HIRE_DATE) AS RUNNING_TOTAL FROM EMPLOYEES ORDER BY HIRE_DATE;
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID,HIRE_DATE,SALARY,SUM(SALARY) OVER ( PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE) AS RUNNING_TOTAL FROM EMPLOYEES;
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID,HIRE_DATE,SALARY,SUM(SALARY) OVER ( PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE DESC)
 AS RUNNING_TOTAL,
ROUND(AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE DESC),2) AS DEPT_AVG_SALARY FROM EMPLOYEES;

/* 3.VALUE FUNCTION LAG() AND LEAD() ACCESS PREVIOUS/NEXT ROW VALUES */
/* LAG() */
SELECT FIRST_NAME,DEPARTMENT_ID,SALARY,LAG(SALARY,1) OVER (ORDER BY SALARY) AS PREV_SALARY FROM EMPLOYEES ORDER BY SALARY;
SELECT FIRST_NAME,DEPARTMENT_ID,SALARY,LAG(SALARY,1) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY) AS PREV_SALARY FROM EMPLOYEES ORDER BY SALARY;
/* LEAD() */
SELECT FIRST_NAME,DEPARTMENT_ID,SALARY,LEAD(SALARY,1) OVER (ORDER BY SALARY) AS PREV_SALARY FROM EMPLOYEES ORDER BY SALARY;
SELECT FIRST_NAME,DEPARTMENT_ID,SALARY,LEAD(SALARY,1) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY) AS PREV_SALARY FROM EMPLOYEES;
USE HR;
/*salary difference */

SELECT FIRST_NAME,DEPARTMENT_ID , SALARY, LAG(SALARY,1) OVER (ORDER BY SALARY) AS LAG_SAL, SALARY - LAG(SALARY,1) OVER
(ORDER BY SALARY) AS SALARY_JUMP FROM EMPLOYEES ORDER BY SALARY; 

SELECT FIRST_NAME,DEPARTMENT_ID , SALARY, LEAD(SALARY,1) OVER (ORDER BY SALARY) AS LEAD_SAL, SALARY - LEAD(SALARY,1) OVER
(ORDER BY SALARY) AS SALARY_JUMP FROM EMPLOYEES ORDER BY SALARY; 

SELECT FIRST_NAME,DEPARTMENT_ID,SALARY, LAG(SALARY,1) OVER (ORDER BY SALARY) AS PREV_SALARY,
LEAD(SALARY,1) OVER (ORDER BY SALARY) AS NEXT_SALARY, SALARY - LAG(SALARY,1) OVER (ORDER BY SALARY) AS SALARY_JUMP, 
LEAD(SALARY,1) OVER (ORDER BY SALARY) - SALARY AS GAP_TO_NEXT FROM EMPLOYEES ORDER BY SALARY; 

/* FIRST VALUE()
 FIND THE FIRST EMPLOYESS HIRED IN EACH DEPARTMENT BASED ON HIRE_DATE*/

SELECT EMPLOYEE_ID , DEPARTMENT_ID , FIRST_NAME , LAST_NAME , HIRE_DATE , FIRST_VALUE(FIRST_NAME) OVER (PARTITION BY DEPARTMENT_ID
ORDER BY HIRE_DATE) AS FIRST_HIRED_IN_DEPT FROM EMPLOYEES;

/*RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW - LAST VALUE()*/
SELECT EMPLOYEE_ID , DEPARTMENT_ID , FIRST_NAME , LAST_NAME , HIRE_DATE , LAST_VALUE(FIRST_NAME) OVER (PARTITION BY DEPARTMENT_ID
ORDER BY HIRE_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LAST_HIRED_IN_DEPT FROM EMPLOYEES;

/* NTILE() - DIVIDE INTO GROUPS; */

SELECT FIRST_NAME,DEPARTMENT_ID,SALARY,NTILE(6) OVER (ORDER BY SALARY DESC) AS SALARY_QUARTILE FROM EMPLOYEES; 

/* VIEW IN SQL */

CREATE VIEW HIGH_SALARY AS 
SELECT EMPLOYEE_ID , FIRST_NAME, LAST_NAME , DEPARTMENT_ID , SALARY FROM EMPLOYEES WHERE SALARY>10000;
SELECT * FROM HIGH_SALARY;
